### ISSUE TITLE
[GabeMZ_SnartFollowers] diagonal movement desync / incompatibility

### ISSUE THREAD

**Issue by xana43** [comuns-rpgmaker/GabeMZ#3]
Issue: 
When I have GALV's Diagonal movement plugin, the followers get a bit confused and walk off on their own directly opposite to where i'm walking diagonally

Steps to reproduce:
Activate this plugin, activate GALV_Diagonal Movement, load into a game, and start walking diagonally

Screenshots:
![image](https://user-images.githubusercontent.com/25046370/101877199-a3bbf900-3b5b-11eb-97a0-8c4d2f616d93.png)

I was just wondering if this is going to be fixed, I perfectly understand if it isn't going to be because A. either the author here doesn't actually update things anymore or B. it's just a simple incompatibility and it either can't or wont be fixed

**Comment by masked-rpgmaker** [comment]
I just opened a PR to fix this, but unfortunately I've stumbled upon yet another issue with GALVs plugin, which makes followers "pop" into position sometimes, causing a weird effect :S

Honestly, I don't really understand what might be the issue, as I read his plugin and could not find anything that would cause this problem; but I've confirmed that simply commenting out his overrides of `Game_CharacterBase#moveDiagonally` and `Game_CharacterBase#moveStraight` resolves this, and his plugin still works for the most part (the diagonal charset thing probably won't work).
